### ISSUE TITLE
Include macro

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digitalmeX#35] opened 2019-03-18 12:16 UTC
Include macro should be extended to allow users to define:
 - organization/repo
 - docsite
 - branch
 - document
 - document part

Please see spec [here](https://github.com/threefoldtech/jumpscaleX/blob/development_types/Jumpscale/tools/markdowndocs/macros/include.md)

**Comment by abom** [comment] 2019-03-19 11:36
Macros tests [are fixed](https://github.com/threefoldtech/jumpscaleX/pull/218/commits/01938670b8b73092b14619bfc874d3b1ebb897d9), they can be used and updated now, also moved test files to tests directory.

**Comment by abom** [comment] 2019-03-19 11:38
Newest specs can be found [here](https://github.com/threefoldtech/jumpscaleX/blob/development_types/docs/tools/wiki/wiki_include.md) and [here](https://github.com/threefoldtech/jumpscaleX/blob/development_types/docs/tools/wiki/code_wiki_parts.md).
Will update the docs in `tools/markdowndocs/macros` and re-link them again at the end.

**Comment by abom** [comment] 2019-03-24 19:11
Should be done now on `development_types`, examples can be found at `docs/tools/wiki/docsites/examples`.
Another problem is the that macros are called 3 times instead of one! found the root cause, will try to fix without any side effects.

**Comment by abom** [comment] 2019-03-24 20:06
> Another problem is the that macros are called 3 times instead of one! found the root cause, will try to fix without any side effects.

This should be fixed now too, processing is done only once.

**Comment by abom** [comment] 2019-03-24 20:07
https://github.com/threefoldtech/jumpscaleX/pull/173

**Comment by abom** [comment] 2019-04-16 12:30
This specs have been changed, closing this in favor of #42.

**Closed as completed by abom** 2019-04-16 12:30 UTC
Labels: priority_major, state_verification, type_feature
